with cohort_operations as 
(
    select * from {{ ref('agg_bod_cohort_detail') }} 
)
SELECT sum(SALES) as SALES ,
        sum(UNSUBSCRIPTIONS) as UNSUBSCRIPTIONS,
        sum(BILLING_SUCCES) as BILLING_SUCCES ,
        sum(REFUNDS) as REFUNDS ,
        sum(VAT_INCLUDED_REFUNDS_LOCAL) as VAT_INCLUDED_REFUNDS_LOCAL ,
        sum(VAT_EXCLUDED_REFUNDS_LOCAL) as VAT_EXCLUDED_REFUNDS_LOCAL ,
        sum(NET_REFUNDS_LOCAL) as NET_REFUNDS_LOCAL ,
        sum(VAT_INCLUDED_INCOME_LOCAL) as VAT_INCLUDED_INCOME_LOCAL ,
        sum(VAT_EXCLUDED_INCOME_LOCAL) as VAT_EXCLUDED_INCOME_LOCAL ,
        sum(NET_INCOME_LOCAL) as NET_INCOME_LOCAL ,
        OPERATION_DATE ,
        COUNTRY ,
        BILLING_CHANNEL ,
        ODCHA_LABEL ,
        FIRM_NAME ,
        CURRENCY ,
        NETWORK_CHANNEL ,
        SERVICE_NAME ,
        FREQY_LABEL ,
        BMODE_LABEL ,
        PROMO ,
        END_USER_PRICE ,
        BILLING_AMOUNT ,
        LB_CLSRV ,
        EXTERNAL_ID ,
        EXTERNAL_ID_PROMO ,
        MERCHANT_ID ,
        CLOFF_ID ,
        SUB_SERVICE_NAME ,
        PAYOU_PAYOUT_RATE ,
        CLSRV_ID ,
        BILLING_PROVIDER ,
        CLIENT_ID ,
        DELAY_WEEK ,
        DELAY_MONTH ,
        DELAY_DAY ,
        WEEKLY_COHORT ,
        WEEKLY_EVENT ,
        MONTHLY_COHORT ,
        MONTHLY_EVENT 
	FROM cohort_operations
	GROUP BY  
        OPERATION_DATE ,
        COUNTRY ,
        BILLING_CHANNEL ,
        ODCHA_LABEL ,
        FIRM_NAME ,
        CURRENCY ,
        NETWORK_CHANNEL ,
        SERVICE_NAME ,
        FREQY_LABEL ,
        BMODE_LABEL ,
        PROMO ,
        END_USER_PRICE ,
        BILLING_AMOUNT ,
        LB_CLSRV ,
        EXTERNAL_ID ,
        EXTERNAL_ID_PROMO ,
        MERCHANT_ID ,
        CLOFF_ID ,
        SUB_SERVICE_NAME ,
        PAYOU_PAYOUT_RATE ,
        CLSRV_ID ,
        BILLING_PROVIDER ,
        CLIENT_ID ,
        DELAY_WEEK ,
        DELAY_MONTH ,
        DELAY_DAY ,
        WEEKLY_COHORT ,
        WEEKLY_EVENT ,
        MONTHLY_COHORT ,
        MONTHLY_EVENT